### ISSUE TITLE
How can I fetch SDN list by ID

### ISSUE THREAD

**Issue by jarvistech229** [InternationalTradeAdministration/developerportal#101]
Hi everyone, I want to fetch SDN list for my application by Id like we can do on ofac 

![Screenshot (1)](https://user-images.githubusercontent.com/58786472/74097590-985f0200-4b33-11ea-8ebe-a7c19e458aae.png)

**Comment by kbecht** [comment]
We do not currently offer searching by SDN ID number as a feature. I have logged this as an enhancement request. 
Notifications of new enhancements are sent out via out email notifications. If you have not already subscribed, we recommend that you [subscribe ](https://public.govdelivery.com/accounts/USITATRADE/subscriber/new?topic_id=USITATRADE_1704) so that you can stay informed regarding any API or portal changes.
