### ISSUE TITLE
CSL API: Document allowed characters for each string request parameter

### ISSUE THREAD

**Issue by mghantous** [InternationalTradeAdministration/developerportal#118]
Please document what characters are allowed for each of the string parameter fields in the CSL API, and also maximum length limits if there are any. The documentation page currently does not specify either:
https://developer.trade.gov/api-details#api=consolidated-screening-list&operation=search

Today we have found that dashes in `state` name lead to a `500` error:

```
curl --location --request GET 'https://data.trade.gov/consolidated_screening_list/v1/search?address=hi&state=--' \
--header 'subscription-key: [redacted]'

{ "statusCode": 500, "message": "Internal server error", "activityId": "0f55fd64-f558-476b-86bb-02cb8eab8552" }
```

I would expect the response to be either a `200` with 0 results, or have a more specific validation error message.

Yesterday parentheses characters (`%28` and `%29` url encoded) within the `address` and `city` parameters were giving `500's` as well, but today are giving `200's`. Was there a fix and where would we find the changelog? Thank you.

**Comment by edsp-david** [comment]
@mghantous Thank you for taking the time to review the new CSL API.
Some of your API requests have helped us identified issues such as the ones that you mentioned above. 

We try not to restrict the request parameters that we receive as long as they are reasonable.
We agree that the response should either be HTTP status 200 or a more specific validation error message.
I believe this issue is fixed.

You can find major updates in https://developer.trade.gov/api-changelog#api=consolidated-screening-list
