### ISSUE TITLE
How to fetch alll the SDN list using the consolidated screening API

### ISSUE THREAD

**Issue by debasish22** [InternationalTradeAdministration/developerportal#119]
I am using the Consolidated screening API - **https://data.trade.gov/consolidated_screening_list/v1/search** and using the source as SDN in the filter which shows the query has 90k records how can i get all the records .

**Comment by jamesisaacs** [comment]
Thank you for taking the time to review our new CSL API.

If you are not searching with name or address related parameters, we recommend downloading our full CSL dataset rather than paging through the search API.

The links are available on the trade.gov Consolidated Screening List page at

https://www.trade.gov/consolidated-screening-list 

Please contact dataservices@trade.gov if you have any questions.

**Comment by patrick-mullen** [comment]
@jamesisaacs How often are these pages updated?
I use to use the `source_last_updated` field in the previous APIs response to determine which sources to pull down but 1) that value appears to have disappeared from search results in the new api and 2) i'm looking to maintain at a minimum daily updates.

**Comment by jamesisaacs** [comment]
@patrick-mullen we check for updates from the data providers and import hourly
