### ISSUE TITLE
CSL API: Request for backwards compatible score values

### ISSUE THREAD

**Issue by mghantous** [InternationalTradeAdministration/developerportal#122]
This is a request to maintain backwards compatibility by keeping the old result `score` values in a result field (e.g. in either the existing `score` field or a new `legacy_score` field).

From the changelog:
> For searches where the name query parameter is not empty and fuzzy_name=true, we have a name score.

With the new `name score`, we've found that a lot of results that had scores of  `75.0` to `85.0` in the old API are now scoring `90` or `100` in the new API (Seems to have lost fractional precision as well. I can provide sample responses if needed). These significantly higher scores are setting off a tremendous amount of red flags in our application. The flags then cause a lot of churn for our teams since there is manual work to review them.

Also `address score` seems to be gone entirely in the new API. I do not see `results.#.score` elements in address searches in the new API, but they exist in the old API. It would be useful to bring those scores back as well because otherwise we have nothing to gauge the precision of the search results.

**Comment by mghantous** [comment]
We've also discovered a potential bug with the new `name score`. 

From the docs:
> We generally break down value in name parameter into tokens separated by whitespaces.
> A result with a name score of 100 means each valid token in the name query parameter has an exact match in a result name or alt_names field.

However, we have a name query with a first and last name separated by whitespace (`%20` encoded but that doesn't seem to make a difference) where we are seeing an unexpected score of 100. The 2nd token (last name) is in both the `alt_names` field and `name` field, but the 1st token (first name) is not in either field. Could you please explain how this could be a 100 when both tokens don't line up in the fields?

**Comment by jamesisaacs** [comment]
Hi @mghantous. Sorry for the slow response. Please email dataservices@trade.gov for a faster response in the future.

We have fixed the bug you reported related to the unexpected score of 100 in the new API. Regarding backwards compatibility, we hope to get there soon. The loss of granularity is due to a lack of per field reporting in the Azure search service. We will update the new system to make it more closely match the old system once Microsoft releases their featuresMode feature for the Search Documents API. It is currently in public preview.
