### ISSUE TITLE
Question about the "Name" key

### ISSUE THREAD

**Issue by JTizzle1875** [InternationalTradeAdministration/developerportal#58]
Hello. I am trying to figure out how to pass both a person's name (first and last) as well as the Company name into the URL for querying the Denied Parties list, but I'm only seeing "Name" as a key for any/all of the lists. How can I pass both the person and company into the query?

**Comment by ErikSArnold** [comment]
Hello. You would build your query like this:

https://api.trade.gov/consolidated_screening_list/search?api_key={your key}&sources= DPL&countries={country code}&name={name}

Basically, you will want to follow the directions for search parameters in order to filter here:

http://developer.trade.gov/consolidated-screening-list.html

Let us know if you have any more questions. 

Thanks,

Erik
