### ISSUE TITLE
Consolidated Screen List Bugginess

### ISSUE THREAD

**Issue by jmuronis** [InternationalTradeAdministration/developerportal#59]
1. If I go to https://www.export.gov/csl-search#/ and type in "Manuel Hernandez" it gives me 1 result.
2. If I put in the address (street only) and search it still returns. 
3. Now, if I were to change "DRIVE" to "DR" all of a sudden I don't get a result anymore
4. If I put in all other matching information such as Phoenix, AZ and zipcode I don't get a result anymore even though the data is a perfect match. Why is this?

**Comment by kbecht** [comment]
@jmuronis I apologize for the delay in us getting back to you. I am assuming that you are running this search with Fuzzy Name set to Off. With fuzzy searching off, the search is exact match only and "Drive" is not an exact match for "Dr". However, if you turn on fuzzy searching, it will find the address with a "Dr" instead of "Drive". Please let me know if that does not help.
