### ISSUE TITLE
Search not producing adequate results

### ISSUE THREAD

**Issue by pmarcusatppbi** [InternationalTradeAdministration/developerportal#61]
We have discovered an issue with the consolidated screening list as follows: 
•	“Gazprom Bank” (with space before “bank”) does not produce results with or without fuzzy logic
•	“Gazprom” does produce results even without adding “Bank”
•	“Gazprombank” does produce results

We tested these against the U.S. Treasury Specially Designated Nationals search engine and all three names as written above, produced similar results. Can you please verify whether this is a programming issue?

**Comment by kbecht** [comment]
Our search function looks for each search term individually. Both terms, “Gazprom” and “Bank” are too different from “Gazprombank” to get a match, even at the maximum fuzzy distance. Using “Gazprom” to find “Gasprombank” would be an insertion of 4, which would result in a score of 60. If you want the search to treat the space as part of the search term rather than separating the search terms, you need to encode it as a special character “Gazprom%20bank”. Searching for “Gazprom%20bank” returns the same result set as “Gazprombank”, only the score is reduced from 100 to 90 based on the insertion of the space.

**Comment by epugh** [comment]
This is going to come over as horrible self promotion, but solving these kinds of problems is what we do, and measuring the impact of these changes is what http://quepid.com/ is for!

**Comment by pmarcusatppbi** [comment]
Thank you Kimberly. I have sent it over to our IT for consideration.

Penny Marcus | 1st VP/BSA Risk & Quality Control Officer
500 E. Esplanade Drive, Suite 500, Oxnard, CA 93036
Direct: (805) 369-5034 | Mobile: (805) 368-1573
www.ppbi.com<http://www.ppbi.com/>
LinkedIn<https://www.linkedin.com/company/pacific-premier-bank>

[https://web.ppbi.com/images/signaturelogos/Standard.png]
