### ISSUE TITLE
Cannot sign-up redux

### ISSUE THREAD

**Issue by jlhall** [InternationalTradeAdministration/developerportal#80]
Howdy! Seeing this issue (originally closed in #76 ) again with a new/non-exploratory email sign up. Same pattern/behavior:

Initial sign up: spins for a bit then 500 error.
Retry: email address already in use error.
Attempt to resend verification email: 500 error.

@jamesisaacs if there's anything else I can provide from the client side to help diagnose this recurrence, please let me know!

Edit: apologies if ITA prefers to re-open issues, rather than creating a new one.

**Comment by kbecht** [comment]
Thank you for letting us know. It seems to be working fine at the moment, but I have asked the technical team to take a look at it.

**Comment by kbecht** [comment]
It appears that at that time there was a significant spike in traffic at that time, resulting in the problems that you saw. Unfortunately, we don't currently have rate limiting on our APIs, which means that this can happen from time to time when the servers are overloaded. We are in the process of upgrading our systems which will give us the ability to set rate limits, preventing this from happening in the future. The rate limits we will be setting will accommodate the normal usage of our current customers. 

I apologize for the inconvenience and recommend that if you haven't done so already, sign up for our [e-mail notifications](https://public.govdelivery.com/accounts/USITATRADE/subscriber/new?topic_id=USITATRADE_1704). We will send out notices prior to making any production changes so that if changes are needed on your end, you will not be surprised and will have time to accommodate the changes.
